#!/bin/bash

###
# chkconfig: 345 20 80
# description: vtxfoo application service script
# processname: java
# chkconfig --add /etc/init.d/vtxfoo
# chkconfig vtxfoo on
#
# Usage: (as root)
# service vtxfoo start
# service vtxfoo stop
# service vtxfoo status
###

PROG="vtxfoo"
APP_DIR="/opt/vtxfoo/"
APP_JAR="${PROG}-fat.jar"
APP_ARGS="-conf /etc/vtxfoo/application-conf.json"
VERTX_OPTS=""
JAVA="/usr/bin/java"

RUNNING_PID="/var/run/${PROG}/${PROG}.pid"
OUT_FILE="/var/log/${PROG}/application.log"
LOCK_FILE="/var/lock/subsys/${PROG}"

# colors
red='\e[0;31m'
green='\e[0;32m'
yellow='\e[0;33m'
reset='\e[0m'

echoRed() { echo -e "${red}$1${reset}"; }
echoGreen() { echo -e "${green}$1${reset}"; }
echoYellow() { echo -e "${yellow}$1${reset}"; }

# Check whether the application is running.
# The check is pretty simple: open a running pid file and check that the process
# is alive.

isrunning() {
    # Check for running app
    if [ -f "$RUNNING_PID" ]; then
        proc=$(cat $RUNNING_PID);
        if /bin/ps --pid $proc 1>&2 >/dev/null;
        then
            return 0
        fi
    fi
    return 1
}


start() {
    if isrunning; then
        echoYellow "${PROG} is already running"
        return 0
    fi

    pushd $APP_DIR > /dev/null
    nohup $JAVA $VERTX_OPTS -jar $APP_JAR $APP_ARGS > $OUT_FILE 2>&1 &
    echo $! > ${RUNNING_PID}
    popd > /dev/null

    if isrunning; then
        echoGreen "${PROG} started"
        touch ${LOCK_FILE}
        exit 0
    else
        echoRed "${PROG} has not started - check log"
        exit 3
    fi
}

restart() {
    echo "Restarting ${PROG}"
    stop
    start
}

stop() {
    echoYellow "Stopping ${PROG}"
    if isrunning; then
        kill `cat $RUNNING_PID`
        rm $RUNNING_PID
    fi
}

status() {
    if isrunning; then
        echoGreen "${PROG} is running"
    else
        echoRed "${PROG} is either stopped or inaccessible"
    fi
}

case "$1" in
    start)
        start
        ;;

    status)
        status
        exit 0
        ;;

    stop)
        if isrunning; then
            stop
            exit 0
        else
            echoRed "Application not running"
            exit 3
        fi
        ;;

    restart)
        stop
        start
        ;;

    *)
        echo "Usage: $0 {status|start|stop|restart}"
        exit 1
esac